### Testar rota de Professores
GET http://localhost:3333/professores

### Testar rota de disciplinas
GET http://localhost:3333/disciplinas

### Testar rota de materiais
GET http://localhost:3333/materiais

### Testar rota de favoritos
GET http://localhost:3333/favoritos