### listar professores
GET http://localhost:3333/professores

### cadastrat professor
POST http://localhost:3333/professores

### editar professor
PUT http://localhost:3333/professores

### remover professor
DELETE http://localhost:3333/professores

### listar favotiros
GET http://localhost:3333/favoritos


### cadastrat favorito
POST http://localhost:3333/favoritos


### editar favorito
PUT http://localhost:3333/favoritos

### remover favoritos
DELETE http://localhost:3333/favoritos

### cadastrar material

POST http://localhost:3333/materiais

### listar materiais
GET http://localhost:3333/materiais

### atualizar materiais
PUT http://localhost:3333/materiais

### deletar materiais
DELETE http://localhost:3333/materiais

### criar disciplinas
POST http://localhost:3333/disciplinas
Content-Type: application/json

{

    "nome" : "topografia"

}

### listar disciplinas
GET http://localhost:3333/disciplinas

### atualizar disciplinas
PUT http://localhost:3333/disciplinas

### deletar disciplinas
DELETE http://localhost:3333/disciplinas